// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package container

import (
	"github.com/taguchi-1/wire-sample/application"
	"github.com/taguchi-1/wire-sample/domain/service"
	"github.com/taguchi-1/wire-sample/infra/persistence"
	"github.com/taguchi-1/wire-sample/interface/handler"
)

// Injectors from wire.go:

func InitializeTodoHandler() handler.Todo {
	todo := persistence.NewTodo()
	serviceTodo := service.NewTodo(todo)
	applicationTodo := application.NewTodo(serviceTodo)
	handlerTodo := handler.NewTodo(applicationTodo)
	return handlerTodo
}

func InitializeTodoService() service.Todo {
	todo := persistence.NewTodo()
	serviceTodo := service.NewTodo(todo)
	return serviceTodo
}
